---
    version: '3'
    services:
      zookeeper:
        image: confluentinc/cp-zookeeper:7.1.0
        hostname: zookeeper
        container_name: zookeeper
        ports:
          - "2181:2181"
        environment:
          ZOOKEEPER_CLIENT_PORT: 2181
          ZOOKEEPER_TICK_TIME: 2000

      broker:
        image: confluentinc/cp-server:7.1.0
        hostname: broker
        container_name: broker
        depends_on:
          - zookeeper
        ports:
          - "9092:9092"
          - "9101:9101"
        environment:
          KAFKA_BROKER_ID: 1
          KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
          KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
          KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
          KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
          KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
          KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
          KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
          KAFKA_JMX_PORT: 9101
          KAFKA_JMX_HOSTNAME: localhost
          KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://schema-registry:8081
          CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker:29092
          CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
          CONFLUENT_METRICS_ENABLE: 'true'
          CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
          KAFKA_CONFLUENT_HTTP_SERVER_LISTENERS: http://localhost:8090
          KAFKA_CONFLUENT_CLUSTER_LINK_ENABLE : 'true'

      schema-registry:
        image: confluentinc/cp-schema-registry:7.1.0
        hostname: schema-registry
        container_name: schema-registry
        depends_on:
          - broker
        ports:
          - "8081:8081"
        environment:
          SCHEMA_REGISTRY_HOST_NAME: schema-registry
          SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'broker:29092'
          SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081

      kafka-connect:
        image: confluentinc/cp-server-connect:7.1.0
        container_name: kafka-connect
        user: root
        depends_on:
          - broker
          - schema-registry
        ports:
          - 8083:8083
          - 9997:9997
        environment:
          CONNECT_BOOTSTRAP_SERVERS: "broker:29092"
          CONNECT_REST_ADVERTISED_HOST_NAME: "kafka-connect"
          CONNECT_REST_PORT: 8083
          CONNECT_GROUP_ID: kafka-connect
          CONNECT_CONFIG_STORAGE_TOPIC: _kafka-connect-configs
          CONNECT_OFFSET_STORAGE_TOPIC: _kafka-connect-offsets
          CONNECT_STATUS_STORAGE_TOPIC: _kafka-connect-status
          CONNECT_KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
          CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'
          CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
          CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'
          CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
          CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
          CONNECT_LOG4J_ROOT_LOGLEVEL: "INFO"
          CONNECT_LOG4J_LOGGERS: "org.apache.kafka.connect.runtime.rest=WARN,org.reflections=ERROR"
          CONNECT_LOG4J_APPENDER_STDOUT_LAYOUT_CONVERSIONPATTERN: "[%d] %p %X{connector.context}%m (%c:%L)%n"
          CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: "1"
          CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: "1"
          CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: "1"
          CONNECT_PLUGIN_PATH: '/usr/share/java/,/usr/share/confluent-hub-components/'
        volumes:
          - $PWD/scripts/:/tmp/scripts/
        command:
          - /tmp/scripts/startKafkaConnectComponents.sh

      ksqldb-server:
        image: confluentinc/cp-ksqldb-server:7.1.0
        hostname: ksqldb-server
        container_name: ksqldb-server
        depends_on:
          - broker
          - kafka-connect
        ports:
          - "8088:8088"
        environment:
          KSQL_CONFIG_DIR: "/etc/ksql"
          KSQL_BOOTSTRAP_SERVERS: "broker:29092"
          KSQL_HOST_NAME: ksqldb-server
          KSQL_LISTENERS: "http://0.0.0.0:8088"
          KSQL_CACHE_MAX_BYTES_BUFFERING: 0
          KSQL_KSQL_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
          KSQL_PRODUCER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor"
          KSQL_CONSUMER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor"
          KSQL_KSQL_CONNECT_URL: "http://kafka-connect:8083"
          KSQL_KSQL_LOGGING_PROCESSING_TOPIC_REPLICATION_FACTOR: 1
          KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: 'true'
          KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: 'true'

      control-center:
        image: confluentinc/cp-enterprise-control-center:7.1.0
        hostname: control-center
        container_name: control-center
        depends_on:
          - broker
          - schema-registry
          - kafka-connect
          - ksqldb-server
        ports:
          - "9021:9021"
        environment:
          CONTROL_CENTER_BOOTSTRAP_SERVERS: 'broker:29092'
          CONTROL_CENTER_CONNECT_CONNECT-DEFAULT_CLUSTER: 'kafka-connect:8083'
          CONTROL_CENTER_KSQL_KSQLDB1_URL: "http://ksqldb-server:8088"
          CONTROL_CENTER_KSQL_KSQLDB1_ADVERTISED_URL: "http://localhost:8088"
          CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
          CONTROL_CENTER_REPLICATION_FACTOR: 1
          CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
          CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
          CONFLUENT_METRICS_TOPIC_REPLICATION: 1
          PORT: 9021

      splunk_uf1:
        image: splunk/universalforwarder:latest
        hostname: splunk_uf1
        container_name: splunk_uf1
        depends_on:
          - kafka-connect
        environment:
          - SPLUNK_START_ARGS=--accept-license
          - SPLUNK_PASSWORD=Password1
          - SPLUNK_APPS_URL=https://raw.githubusercontent.com/JohnnyMirza/confluent_splunk_demo/main/palo-alto-networks-add-on-for-splunk_710.tgz,https://raw.githubusercontent.com/JohnnyMirza/confluent_splunk_demo/main/splunk-add-on-for-cisco-asa_410.tgz
        volumes:
          - $PWD/splunk-uf1/:/opt/splunkforwarder/etc/apps/splunk-uf1/
        ports:
          - 3333:3333
          - 3334:3334
          - 3335:3335

      splunk_eventgen:
        image: guilhemmarchand/splunk-eventgen:latest
        container_name: splunk_eventgen
        restart: unless-stopped
        user: 'root'
        volumes:
          - $PWD/splunk-eventgen/:/opt/splunk-eventgen
        ports:
          - 6379:6379
          - 9500:9500
        depends_on:
          - splunk_uf1
        command: 'splunk_eventgen -v generate /opt/splunk-eventgen/default/eventgen.conf'

      splunk_search:
        image: splunk/splunk:latest
        container_name: splunk_search
        user: 'root'
        volumes:
          - $PWD/splunk-search/:/opt/splunk/etc/apps/splunk-search/
        depends_on:
          - kafka-connect
        environment:
          - SPLUNK_START_ARGS=--accept-license
          # - SPLUNK_HEC_TOKEN=3bca5f4c-1eff-4eee-9113-ea94c284478a
          - SPLUNK_APPS_URL=https://raw.githubusercontent.com/jlamcon/confluent_splunk_demo/master/palo-alto-networks-add-on-for-splunk_710.tgz,https://raw.githubusercontent.com/JohnnyMirza/confluent_splunk_demo/main/splunk-add-on-for-cisco-asa_410.tgz
          - SPLUNK_PASSWORD=Password1
        ports:
          - 8089:8088
          - 8000:8000

      cyber-sigma-streams:
        image: michaelpeacock/confluent-sigma:v1
        container_name: cyber-sigma-streams
        depends_on:
          - broker
          - kafka-connect
          - control-center
          - ksqldb-server
        hostname: cyber-sigma-streams
        volumes:
          - $PWD/scripts/:/tmp/config
        command:
          - bash
          - -c
          - |
            echo "Starting Streams app..."
            cd /tmp
            java -cp kafka-sigma-streams-1.0-fat.jar io.confluent.sigmarules.SigmaStreamsApp -c /tmp/config/sigma-dns.properties
            sleep infinity

      cyber-sigma-regex-ui:
        image: michaelpeacock/confluent-sigma-regex-ui:latest
        container_name: cyber-sigma-regex-ui
        depends_on:
          - broker
          - kafka-connect
          - control-center
          - ksqldb-server
        hostname: cyber-sigma-regex-ui
        ports:
          - 8080:8080
        environment:
          kafka_bootstrapAddress: 'broker:29092'
          kafka_schemaRegistry: 'http://schema-registry:8081'
          kafka_sigma_rules_topic: 'sigma-rules'
          confluent_regex_applicationID: 'regex-application'
          confluent_regex_inputTopic: 'splunk-s2s-events'
          confluent_regex_ruleTopic: 'regex-rules'
          confluent_regex_filterField: 'sourcetype'
          confluent_regex_regexField: 'event'
