---
    version: '3' 
    services:
      zookeeper:
        image: confluentinc/cp-zookeeper:latest
        container_name: zookeeper
        environment:
          ZOOKEEPER_CLIENT_PORT: 2181

      broker:
        image: confluentinc/cp-kafka:latest
        container_name: broker
        depends_on:
          - zookeeper
        ports:
          - 9092:9092
        environment:
          KAFKA_BROKER_ID: 1
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
          KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
          KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
          KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
          KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
          KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 100

      schema-registry:
        image: confluentinc/cp-schema-registry:latest
        container_name: schema-registry
        depends_on:
          - zookeeper
          - broker
        ports:
          - 8081:8081
        environment:
          SCHEMA_REGISTRY_HOST_NAME: schema-registry
          SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181

      kafka-connect:
        image: confluentinc/cp-kafka-connect:latest
        container_name: kafka-connect
        user: root
        depends_on:
          - broker
          - schema-registry
        ports:
          - 8083:8083
        environment:
          CONNECT_BOOTSTRAP_SERVERS: "broker:29092"
          CONNECT_REST_ADVERTISED_HOST_NAME: "kafka-connect"
          CONNECT_REST_PORT: 8083
          CONNECT_GROUP_ID: kafka-connect
          CONNECT_CONFIG_STORAGE_TOPIC: _kafka-connect-configs
          CONNECT_OFFSET_STORAGE_TOPIC: _kafka-connect-offsets
          CONNECT_STATUS_STORAGE_TOPIC: _kafka-connect-status
          CONNECT_KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
          CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'
          CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
          CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'
          CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
          CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
          CONNECT_LOG4J_ROOT_LOGLEVEL: "INFO"
          CONNECT_LOG4J_LOGGERS: "org.apache.kafka.connect.runtime.rest=WARN,org.reflections=ERROR"
          CONNECT_LOG4J_APPENDER_STDOUT_LAYOUT_CONVERSIONPATTERN: "[%d] %p %X{connector.context}%m (%c:%L)%n"
          CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: "1"
          CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: "1"
          CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: "1"
          CONNECT_PLUGIN_PATH: '/usr/share/java/,/usr/share/confluent-hub-components/'
        volumes:
          - $PWD/scripts/:/tmp/scripts/
        command: 
          - /tmp/scripts/startKafkaConnectComponents.sh  
      ksqldb:
        image: confluentinc/cp-ksqldb-server:latest
        hostname: ksqldb
        container_name: ksqldb
        depends_on:
          - broker
          - kafka-connect
        ports:
          - "8088:8088"
        environment:
          KSQL_LISTENERS: http://0.0.0.0:8088
          KSQL_BOOTSTRAP_SERVERS: broker:29092
          KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: "true"
          KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: "true"
          KSQL_KSQL_CONNECT_URL: http://kafka-connect:8083
          KSQL_KSQL_SCHEMA_REGISTRY_URL: http://schema-registry:8081
          KSQL_KSQL_SERVICE_ID: confluent_ksqldb_01
          KSQL_KSQL_HIDDEN_TOPICS: '^_.*'
    
      control-center:
       image: confluentinc/cp-enterprise-control-center:latest
       hostname: control-center
       container_name: control-center
       user: root
       depends_on:
         - broker
         - schema-registry
         - kafka-connect
       ports:
         - 9021:9021
       environment:
         CONTROL_CENTER_BOOTSTRAP_SERVERS: broker:29092
         CONTROL_CENTER_REPLICATION_FACTOR: 1
         CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
         CONTROL_CENTER_METRICS_TOPIC_PARTITIONS: 1
         CONTROL_CENTER_STREAMS_CACHE_MAX_BYTES_BUFFERING: 100000000
         CONTROL_CENTER_STREAMS_CONSUMER_REQUEST_TIMEOUT_MS: "960032"
         CONTROL_CENTER_STREAMS_NUM_STREAM_THREADS: 1
         CONTROL_CENTER_REST_LISTENERS: http://0.0.0.0:9021
         CONTROL_CENTER_CONNECT_CONNECT1_CLUSTER: http://kafka-connect:8083
         CONTROL_CENTER_KSQL_SERVER_URL: http://ksqldb:8088
         CONTROL_CENTER_SCHEMA_REGISTRY_SR1_URL: http://schema-registry:8081
         CONTROL_CENTER_KSQL_SERVER_ADVERTISED_URL: http://localhost:8088
    
      splunk_uf1:
        image: splunk/universalforwarder:latest
        hostname: splunk_uf1
        container_name: splunk_uf1
        depends_on:
          - kafka-connect
        environment:
          - SPLUNK_START_ARGS=--accept-license
          - SPLUNK_PASSWORD=Password1
        volumes:
          - $PWD/splunk-uf1/:/opt/splunkforwarder/etc/apps/splunk-uf1/
        ports:
          - 3333:3333
      
      splunk_eventgen:
        image: guilhemmarchand/splunk-eventgen:latest
        container_name: splunk_eventgen
        restart: unless-stopped
        user: 'root'
        volumes:
          - $PWD/splunk-eventgen/:/opt/splunk-eventgen
        ports:
          - 6379:6379
          - 9500:9500
        depends_on:
          - splunk_uf1
        command: 'splunk_eventgen -v generate /opt/splunk-eventgen/default/eventgen.conf'
      
      splunk_search:
        image: splunk/splunk:latest
        container_name: splunk_search
        depends_on:
          - kafka-connect
        environment:
          - SPLUNK_START_ARGS=--accept-license
          - SPLUNK_HEC_TOKEN=3bca5f4c-1eff-4eee-9113-ea94c284478a
          - SPLUNK_APPS_URL=https://raw.githubusercontent.com/JohnnyMirza/confluent_splunk_demo/main/splunk-add-on-for-cisco-asa_410.tgz
          - SPLUNK_PASSWORD=Password1
        ports:
          - 8089:8088
          - 8000:8000
          - 9997:9997
